// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAni4w1YgPEXFQBwF9FEJnV3al85LmXMgE',
    appId: '1:332219024896:web:403c678c9371437191fae5',
    messagingSenderId: '332219024896',
    projectId: 'travel-1ed8d',
    authDomain: 'travel-1ed8d.firebaseapp.com',
    storageBucket: 'travel-1ed8d.firebasestorage.app',
    measurementId: 'G-73SR9V8BRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1axywUAPn6qIIqGT7LvT5xuH8S24FLxc',
    appId: '1:332219024896:android:dd1de104ea17f35891fae5',
    messagingSenderId: '332219024896',
    projectId: 'travel-1ed8d',
    storageBucket: 'travel-1ed8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJHYAa3t10NdW9isoP5485BWrnTV3mUrs',
    appId: '1:332219024896:ios:66bb3ccab4f5199791fae5',
    messagingSenderId: '332219024896',
    projectId: 'travel-1ed8d',
    storageBucket: 'travel-1ed8d.firebasestorage.app',
    iosBundleId: 'com.example.traveles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJHYAa3t10NdW9isoP5485BWrnTV3mUrs',
    appId: '1:332219024896:ios:66bb3ccab4f5199791fae5',
    messagingSenderId: '332219024896',
    projectId: 'travel-1ed8d',
    storageBucket: 'travel-1ed8d.firebasestorage.app',
    iosBundleId: 'com.example.traveles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAni4w1YgPEXFQBwF9FEJnV3al85LmXMgE',
    appId: '1:332219024896:web:5683a4c6325c05e591fae5',
    messagingSenderId: '332219024896',
    projectId: 'travel-1ed8d',
    authDomain: 'travel-1ed8d.firebaseapp.com',
    storageBucket: 'travel-1ed8d.firebasestorage.app',
    measurementId: 'G-9F8CB5P89B',
  );
}
